export const tools = [
  {
    name: "AI Reel Script Generator",
    slug: "ai-reel-script-generator",
    description: "Generate viral reel scripts for Instagram, YouTube Shorts and Facebook Reels.",
    placeholder: "Example: motivational video about small town boy big dreams",
    guide: "Enter your topic, select video duration and generate a short engaging script with hook, body and ending.",
  },
  {
    name: "Viral Caption Generator",
    slug: "viral-caption-generator",
    description: "Create catchy captions for Instagram reels and YouTube Shorts.",
    placeholder: "Example: villain walking video caption",
    guide: "Write your video idea and get multiple viral caption options.",
  },
  {
    name: "Hashtag Generator",
    slug: "hashtag-generator",
    description: "Generate niche-based hashtags for better reach.",
    placeholder: "Example: fashion reels, motivation, AI content",
    guide: "Enter your niche and get relevant hashtags for social media.",
  },
  {
    name: "Hook Generator",
    slug: "hook-generator",
    description: "Create powerful first 3-second hooks for videos.",
    placeholder: "Example: sad love story hook",
    guide: "Use hooks at the start of videos to increase watch time.",
  },
  {
    name: "Thumbnail Text Generator",
    slug: "thumbnail-text-generator",
    description: "Generate clickable thumbnail text ideas.",
    placeholder: "Example: AI video creation tutorial",
    guide: "Enter your video topic and get emotional, curiosity-based thumbnail text.",
  },
  {
    name: "AI Video Prompt Generator",
    slug: "ai-video-prompt-generator",
    description: "Generate prompts for Kling, Veo, Runway and Hailuo AI.",
    placeholder: "Example: cinematic hero walking scene",
    guide: "Describe your scene and generate cinematic AI video prompts.",
  },
  {
    name: "YouTube SEO Generator",
    slug: "youtube-seo-generator",
    description: "Generate YouTube titles, descriptions and tags.",
    placeholder: "Example: how to create AI reels",
    guide: "Use this tool to optimize YouTube videos for search.",
  },
  {
    name: "Bio Generator",
    slug: "bio-generator",
    description: "Create professional Instagram and YouTube bios.",
    placeholder: "Example: AI content creator bio",
    guide: "Enter your profession or niche and get bio ideas.",
  },
  {
    name: "UGC Ad Script Generator",
    slug: "ugc-ad-script-generator",
    description: "Generate ad scripts for affiliate and product promotion.",
    placeholder: "Example: college admission ad script",
    guide: "Use this for product ads, affiliate campaigns and creator promotions.",
  },
];